### ISSUE TITLE
Question on Proj Structure

### ISSUE THREAD

**Issue by renweview** [Joshmantova/Eagle-Vision#2]
Hey Josh, wondering why you used Docker for the Eagle Vision project? Any alternatives? Thanks!

**Comment by josh-mantovani** [comment]
I used Docker because it's a great tool for building out the needed environment including all requirements and because it integrates well with other tools I used here such as Streamlit. I could have built a virtual machine instead, but it would have been more work for no benefit.

**Comment by SatvikSri** [comment]
Hey Josh, I am not able to fetch the images from AWS using the streamlit
![Screenshot (41)](https://user-images.githubusercontent.com/82564404/219966400-3420dea3-4c30-4b8a-bcd9-11af92dc57e7.png)

**Comment by Joshmantova** [comment]
Closing out but let me know if you have more questions.
